name: Just testin a thing

on:
  workflow_dispatch:

jobs:
  slack-wordle:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - run: |
          which jq
          jq --version
          jq
