name: Debug - Answer

on:
  workflow_dispatch:
    inputs:
      channel:
        required: true
        type: choice
        options:
          - '#wordle-test C040V2HQCQ0'
          - '#wordle C02U5D1MYKY'
      answer:
        required: true
        type: text

env:
  SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
  BOT_ID: 'B03VB855JSY'

jobs:
  slack-wordle:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - run: |
          ANSWER=${{ inputs.answer }}
          CHANNEL=$(echo "${{ inputs.channel }}" | awk '{print $2}')

          MSG=$(curl --silent -H "Authorization: Bearer $SLACK_TOKEN" "https://slack.com/api/conversations.history?channel=$CHANNEL" | jq -c "[.messages[] | select(.bot_id == \"$BOT_ID\")][0]")

          ANSWER_DATA='{"text":'$(echo $MSG | jq '.text' | sed "s/?????/$ANSWER/")',"channel":"'$CHANNEL'","ts":'$(echo $MSG | jq '.ts')'}'
          curl --silent -X POST -H 'Content-type: application/json; charset=utf-8' -H "Authorization: Bearer $SLACK_TOKEN" --data "$ANSWER_DATA" "https://slack.com/api/chat.update"
