name: Keep alive
on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  keep-alive:
    name: Keep Alive
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: gautamkrishnar/keepalive-workflow@v1
