name: Post Slack Wordle

on:
  schedule:
    - cron: '30 6 * * *'
  workflow_dispatch:

env:
  SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}

jobs:
  slack-wordle:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - run: |
          NUMBER=$(curl --silent --head "https://wordle.dallin.pro/?date=$(TZ=UTC date +'%m/%d/%Y')" | grep x-days-from | awk '{print $2}' | tr -d '\r')

          curl --silent -X POST -H 'Content-type: application/json; charset=utf-8' -H "Authorization: Bearer $SLACK_TOKEN" --data '{"text":"Wordle '"$NUMBER"' - ?????","channel":"C02U5D1MYKY"}' "https://slack.com/api/chat.postMessage"
