name: Post Slack Wordle

on:
  schedule:
    - cron: '30 6 * * *'

env:
  SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
  CHANNEL: 'C02U5D1MYKY'
  BOT_ID: 'B03VB855JSY'

jobs:
  slack-wordle:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - run: |
          ANSWER=$(curl --silent "https://www.nytimes.com/svc/wordle/v2/$(TZ=HST date +'%Y-%m-%d').json" | jq -r .solution)
          NUMBER=$(curl --silent --head "https://wordle.dallin.pro/?date=$(TZ=UTC date +'%m/%d/%Y')" | grep x-days-from | awk '{print $2}' | tr -d '\r')

          MSG=$(curl --silent -H "Authorization: Bearer $SLACK_TOKEN" "https://slack.com/api/conversations.history?channel=$CHANNEL" | jq -c "[.messages[] | select(.bot_id == \"$BOT_ID\")][0]")

          ANSWER_DATA='{"text":'$(echo $MSG | jq '.text' | sed "s/?????/$ANSWER/")',"channel":"'$CHANNEL'","ts":'$(echo $MSG | jq '.ts')'}'
          curl --silent -X POST -H 'Content-type: application/json; charset=utf-8' -H "Authorization: Bearer $SLACK_TOKEN" --data "$ANSWER_DATA" "https://slack.com/api/chat.update"

          QUESTION_DATA='{"text":"Wordle '"$NUMBER"' - ?????","channel":"'$CHANNEL'"}'
          curl --silent -X POST -H "Content-type: application/json; charset=utf-8" -H "Authorization: Bearer $SLACK_TOKEN" --data "$QUESTION_DATA" "https://slack.com/api/chat.postMessage"
