name: Post Slack Wordle

on:
  schedule:
    - cron: '30 6 * * *'
  workflow_dispatch:

jobs:
  slack-wordle:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - run: |
          ANSWER=$(TZ=HST curl "https://wordle.dallin.pro/?date=$(date +'%m/%d/%Y')")
          NUMBER=$(TZ=HST curl --head --silent "https://wordle.dallin.pro/?date=$(date +'%m/%d/%Y')" | grep x-days-from | awk '{print $2}')
          echo '$NUMBER: $ANSWER'
