name: Post Slack Wordle

on:
  schedule:
    - cron: '30 6 * * *'
  workflow_dispatch:

env:
  SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}

jobs:
  slack-wordle:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - run: |
          ANSWER=$(curl --silent "https://wordle.dallin.pro/?date=$(TZ=HST date +'%m/%d/%Y')")
          NUMBER=$(curl --silent --head "https://wordle.dallin.pro/?date=$(TZ=UTC date +'%m/%d/%Y')" | grep x-days-from | awk '{print $2}' | tr -d '\r')

          MSG=$(curl --silent -H "Authorization: Bearer $SLACK_TOKEN" "https://slack.com/api/conversations.history?channel=C02U5D1MYKY" | jq -c '[.messages[] | select(.bot_id == "B03VB855JSY")][0]')

          curl --silent -X POST -H 'Content-type: application/json; charset=utf-8' -H "Authorization: Bearer $SLACK_TOKEN" --data '{"text":'$(echo $MSG | jq '.text' | sed "s/?????/$ANSWER/")',"channel":"C02U5D1MYKY","ts":'$(echo $MSG | jq '.ts')'}' "https://slack.com/api/chat.update"

          curl --silent -X POST -H 'Content-type: application/json; charset=utf-8' -H "Authorization: Bearer $SLACK_TOKEN" --data '{"text":"Wordle '"$NUMBER"' - ?????","channel":"C02U5D1MYKY"}' "https://slack.com/api/chat.postMessage"
